global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using Ecom.DAL.Database;
global using System.Linq.Expressions;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;